[Interface]
PrivateKey = sEPvvpROhgwPOtOkcOlophVQl9u0V1C4W+Bxcoi483Y=
Address = 10.0.0.3/24
DNS = 8.8.8.8, 8.8.4.4

[Peer]
PublicKey = My8Gu4G1hEuVk4C/9JeKfBfXRpIzCiapxM+cUjx/H34=
Endpoint = 157.245.195.58:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
