"""initial_all_models

Revision ID: ee7f5624b51a
Revises: 
Create Date: 2026-04-25 15:05:08.574161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee7f5624b51a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensitive_words',
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensitive_words_word'), 'sensitive_words', ['word'], unique=True)
    op.create_table('strategy_entries',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('extracted_pattern', sa.Text(), nullable=False),
    sa.Column('pattern_type', sa.String(length=30), nullable=True),
    sa.Column('emotional_curve', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sentence_templates', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_entries_category'), 'strategy_entries', ['category'], unique=False)
    op.create_index(op.f('ix_strategy_entries_title'), 'strategy_entries', ['title'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('quota_total', sa.Integer(), nullable=False),
    sa.Column('quota_used', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('guest_identities',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('personality', sa.String(length=200), nullable=True),
    sa.Column('core_issue', sa.Text(), nullable=False),
    sa.Column('speaking_style', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_materials',
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('extracted_strategies', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('global_style', sa.Text(), nullable=False),
    sa.Column('catchphrases', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('reaction_patterns', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sentence_templates', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('core_values', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('language_style', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tone_adaptation', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_name'), 'personas', ['name'], unique=True)
    op.create_table('room_tones',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('core_rules', sa.Text(), nullable=False),
    sa.Column('forbidden_topics', sa.Text(), nullable=True),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_tones_name'), 'room_tones', ['name'], unique=True)
    op.create_table('persona_slices',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('emotion_tag', sa.String(length=50), nullable=True),
    sa.Column('action_desc', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_projects',
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('tone_id', sa.UUID(), nullable=True),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('persona_version', sa.Integer(), nullable=True),
    sa.Column('script_content', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('emotion_curve', sa.String(length=100), nullable=True),
    sa.Column('strategy_mix', sa.String(length=100), nullable=True),
    sa.Column('multi_version', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('sensitive_hits', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['guest_identities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['script_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tone_id'], ['room_tones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('script_projects')
    op.drop_table('persona_slices')
    op.drop_index(op.f('ix_room_tones_name'), table_name='room_tones')
    op.drop_table('room_tones')
    op.drop_index(op.f('ix_personas_name'), table_name='personas')
    op.drop_table('personas')
    op.drop_table('learning_materials')
    op.drop_table('guest_identities')
    op.drop_table('users')
    op.drop_index(op.f('ix_strategy_entries_title'), table_name='strategy_entries')
    op.drop_index(op.f('ix_strategy_entries_category'), table_name='strategy_entries')
    op.drop_table('strategy_entries')
    op.drop_index(op.f('ix_sensitive_words_word'), table_name='sensitive_words')
    op.drop_table('sensitive_words')
    # ### end Alembic commands ###
